# Generated by Django 6.0.6 on 2026-07-05 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('PHOTO', 'Fotografía'), ('VIDEO', 'Video')], default='PHOTO', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Sube una imagen si el tipo es Fotografía', null=True, upload_to='galleries/')),
                ('video_url', models.URLField(blank=True, help_text='Enlace de YouTube/Vimeo si el tipo es Video', null=True)),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Pie de foto/video')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden en la galería')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='invitations.invitation')),
            ],
            options={
                'verbose_name': 'Elemento de Galería',
                'verbose_name_plural': 'Galería',
                'ordering': ['order', 'id'],
            },
        ),
    ]
