# Generated by Django 6.0.6 on 2026-07-05 04:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='URL amigable (ej. mis-xv-natalia)', max_length=150, unique=True)),
                ('host_name', models.CharField(max_length=100, verbose_name='Nombre del Festejado(a)')),
                ('event_type', models.CharField(choices=[('XV', 'XV Años'), ('BODA', 'Boda'), ('BAUTIZO', 'Bautizo'), ('CUMPLE', 'Cumpleaños'), ('OTRO', 'Otro Evento Social')], default='XV', max_length=20)),
                ('template_choice', models.CharField(choices=[('xv_natali', 'Plantilla 1: Diseño Floral (Colibrí)'), ('boda_elegante', 'Plantilla 2: Boda Minimalista'), ('generica', 'Plantilla 3: Fiesta General')], default='xv_natali', max_length=50)),
                ('event_date', models.DateField(verbose_name='Fecha del Evento')),
                ('event_time', models.TimeField(verbose_name='Hora del Evento')),
                ('google_maps_url', models.URLField(blank=True, null=True, verbose_name='Enlace de Google Maps')),
                ('dress_code', models.CharField(blank=True, max_length=150, null=True, verbose_name='Código de Vestimenta')),
                ('custom_primary_color', models.CharField(default='#000000', max_length=7, verbose_name='Color Primario (HEX)')),
                ('custom_secondary_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Color Secundario (HEX)')),
                ('music_url', models.URLField(blank=True, null=True, verbose_name='Enlace a música (Spotify/Audio)')),
                ('show_countdown', models.BooleanField(default=True, verbose_name='Mostrar Contador')),
                ('show_location', models.BooleanField(default=True, verbose_name='Mostrar Ubicación')),
                ('show_history', models.BooleanField(default=True, verbose_name='Mostrar Historia')),
                ('show_gallery', models.BooleanField(default=True, verbose_name='Mostrar Galería')),
                ('show_sponsors', models.BooleanField(default=True, verbose_name='Mostrar Padrinos')),
                ('show_program', models.BooleanField(default=True, verbose_name='Mostrar Programa')),
                ('show_gift_table', models.BooleanField(default=True, verbose_name='Mostrar Mesa de Regalos')),
                ('show_music', models.BooleanField(default=True, verbose_name='Reproducir Música')),
                ('show_rsvp', models.BooleanField(default=True, verbose_name='Mostrar RSVP')),
                ('show_dress_code', models.BooleanField(default=True, verbose_name='Mostrar Código de Vestimenta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invitación',
                'verbose_name_plural': 'Invitaciones',
            },
        ),
        migrations.CreateModel(
            name='GiftRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name_or_store', models.CharField(max_length=100, verbose_name='Banco o Tienda')),
                ('account_or_link', models.CharField(max_length=255, verbose_name='No. de Cuenta / Enlace')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_registries', to='invitations.invitation')),
            ],
            options={
                'verbose_name': 'Mesa de Regalo / Cuenta',
                'verbose_name_plural': 'Mesa de Regalos',
            },
        ),
        migrations.CreateModel(
            name='ProgramEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_events', to='invitations.invitation')),
            ],
            options={
                'verbose_name': 'Evento del Programa',
                'verbose_name_plural': 'Programa del Evento',
                'ordering': ['order', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(help_text='Ej. Padrinos de Velación', max_length=150)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='invitations.invitation')),
            ],
            options={
                'verbose_name': 'Padrino',
                'verbose_name_plural': 'Padrinos',
            },
        ),
    ]
