# Generated by Django 6.0.6 on 2026-07-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftregistry',
            name='account_or_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='No. de Cuenta / Enlace'),
        ),
        migrations.AlterField(
            model_name='giftregistry',
            name='bank_name_or_store',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco o Tienda'),
        ),
    ]
