# Generated by Django 6.0.6 on 2026-07-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_alter_giftregistry_account_or_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_images/', verbose_name='Imagen Principal (Fondo)'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='custom_primary_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Color Primario (HEX)'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='custom_secondary_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Color Secundario (HEX)'),
        ),
    ]
