# Generated by Django 6.0.6 on 2026-07-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_invitation_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='hero_image_position',
            field=models.CharField(choices=[('center', 'Centro (Recomendado)'), ('top', 'Arriba'), ('bottom', 'Abajo'), ('left', 'Izquierda'), ('right', 'Derecha')], default='center', max_length=10, verbose_name='Alineación del Fondo'),
        ),
    ]
