# Generated by Django 6.0.6 on 2026-07-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_invitation_hero_image_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='rsvp_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora Límite de Confirmación (RSVP)'),
        ),
    ]
