# Generated by Django 6.0.6 on 2026-07-06 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0005_invitation_rsvp_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='show_parents',
            field=models.BooleanField(default=False, verbose_name='Mostrar Padres'),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(help_text='Ej. Padres de la Novia, Padres del Novio', max_length=150)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='invitations.invitation')),
            ],
            options={
                'verbose_name': 'Padre/Madre',
                'verbose_name_plural': 'Padres',
            },
        ),
    ]
