# Generated by Django 6.0.6 on 2026-07-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0006_invitation_show_parents_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='order_countdown',
            field=models.PositiveIntegerField(default=10, verbose_name='Orden Contador'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='order_dress_code',
            field=models.PositiveIntegerField(default=80, verbose_name='Orden Código de Vestimenta'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='order_gallery',
            field=models.PositiveIntegerField(default=60, verbose_name='Orden Galería'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='order_gift_table',
            field=models.PositiveIntegerField(default=70, verbose_name='Orden Mesa de Regalos'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='order_location',
            field=models.PositiveIntegerField(default=20, verbose_name='Orden Ubicación'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='order_parents',
            field=models.PositiveIntegerField(default=40, verbose_name='Orden Padres'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='order_program',
            field=models.PositiveIntegerField(default=30, verbose_name='Orden Programa'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='order_rsvp',
            field=models.PositiveIntegerField(default=90, verbose_name='Orden Confirmación (RSVP)'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='order_sponsors',
            field=models.PositiveIntegerField(default=50, verbose_name='Orden Padrinos'),
        ),
    ]
