# Generated by Django 6.0.6 on 2026-07-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0007_invitation_order_countdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='ceremony_google_maps_url',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace de Google Maps (Ceremonia)'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='ceremony_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de Iglesia/Templo (Ceremonia)'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='ceremony_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de la Ceremonia'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='order_ceremony',
            field=models.PositiveIntegerField(default=15, verbose_name='Orden Ceremonia'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='show_ceremony',
            field=models.BooleanField(default=False, verbose_name='Mostrar Ceremonia Religiosa'),
        ),
    ]
