# Generated by Django 6.0.6 on 2026-07-07 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0008_invitation_ceremony_google_maps_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='section_background_image',
            field=models.ImageField(blank=True, help_text='Opcional. Reemplaza el patrón de fondo estandar de las secciones.', null=True, upload_to='backgrounds/', verbose_name='Imagen de Fondo para Secciones'),
        ),
        migrations.CreateModel(
            name='SeparatorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='separators/', verbose_name='Imagen Separadora')),
                ('order', models.PositiveIntegerField(default=25, verbose_name='Orden (Posición)')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separator_images', to='invitations.invitation')),
            ],
            options={
                'verbose_name': 'Imagen Separadora',
                'verbose_name_plural': 'Imágenes Separadoras',
                'ordering': ['order'],
            },
        ),
    ]
