# Generated by Django 6.0.6 on 2026-07-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0009_invitation_section_background_image_separatorimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='location_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Lugar de Recepción'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='google_maps_url',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace de Google Maps (Recepción)'),
        ),
    ]
