# Generated by Django 6.0.6 on 2026-07-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0010_invitation_location_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='closing_message',
            field=models.TextField(blank=True, help_text='Ej. ¡Te espero con mucho anhelo y emoción... NO FALTES!', null=True, verbose_name='Mensaje de Despedida'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='order_closing_message',
            field=models.PositiveIntegerField(default=100, verbose_name='Orden Mensaje de Despedida'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='show_closing_message',
            field=models.BooleanField(default=True, verbose_name='Mostrar Mensaje de Despedida'),
        ),
    ]
