# Generated by Django 6.0.6 on 2026-07-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0011_invitation_closing_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='music_file',
            field=models.FileField(blank=True, null=True, upload_to='music/', verbose_name='Archivo de Música MP3'),
        ),
    ]
