# Generated by Django 6.0.6 on 2026-07-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0012_invitation_music_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='default_pdf_message',
            field=models.TextField(default='Te invitamos cordialmente a celebrar este día tan especial con nosotros. Tu presencia es el mejor regalo.', verbose_name='Mensaje de Pase PDF por defecto'),
        ),
    ]
