# Generated by Django 6.0.6 on 2026-07-11 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0013_invitation_default_pdf_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Usuario cliente que administra esta invitación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to=settings.AUTH_USER_MODEL, verbose_name='Propietario / Cliente'),
        ),
    ]
