# Generated by Codex on 2026-07-14

from django.db import migrations, models
import django.db.models.deletion


FORMAL_MESSAGE = """{guest_name}

Nos complace invitarte a unirte a nosotros en el día más especial de nuestras vidas.
Nos casamos el {event_date}.

Estamos emocionados de compartir este momento con personas tan queridas y valoramos tu presencia en nuestra celebración.

Por favor, confirma tu asistencia antes del {rsvp_deadline} para que podamos hacer los preparativos necesarios.

Ver invitación:
{invitation_url}

Esperamos verte pronto y celebrar juntos este hermoso día."""


SHORT_MESSAGE = """Hola {guest_name}.

Con mucha alegría queremos invitarte a nuestra celebración el {event_date}.

Puedes ver todos los detalles y confirmar tu asistencia aquí:
{invitation_url}

Por favor confirma antes del {rsvp_deadline}."""


WARM_MESSAGE = """{guest_name}, queremos compartir contigo una noticia muy especial.

Celebraremos este momento tan importante el {event_date} y nos encantaría contar con tu presencia.

Consulta la invitación y confirma tu asistencia aquí:
{invitation_url}

Te pedimos confirmar antes del {rsvp_deadline}.

Será una gran alegría verte ese día."""


def seed_first_invitation_messages(apps, schema_editor):
    Invitation = apps.get_model('invitations', 'Invitation')
    InvitationWhatsAppMessage = apps.get_model('invitations', 'InvitationWhatsAppMessage')
    invitation = Invitation.objects.order_by('created_at', 'host_name').first()
    if not invitation or InvitationWhatsAppMessage.objects.filter(invitation=invitation).exists():
        return

    InvitationWhatsAppMessage.objects.bulk_create([
        InvitationWhatsAppMessage(
            invitation=invitation,
            title='Mensaje formal',
            body=FORMAL_MESSAGE,
            is_default=True,
            is_active=True,
            order=1,
        ),
        InvitationWhatsAppMessage(
            invitation=invitation,
            title='Mensaje corto',
            body=SHORT_MESSAGE,
            is_default=False,
            is_active=True,
            order=2,
        ),
        InvitationWhatsAppMessage(
            invitation=invitation,
            title='Mensaje cálido',
            body=WARM_MESSAGE,
            is_default=False,
            is_active=True,
            order=3,
        ),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0015_replace_owner_with_administrators'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationWhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('body', models.TextField(help_text='Variables disponibles: {guest_name}, {guest_alias}, {event_name}, {event_date}, {event_time}, {rsvp_deadline}, {invitation_url}', verbose_name='Mensaje')),
                ('is_default', models.BooleanField(default=False, verbose_name='Mensaje por defecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='invitations.invitation')),
            ],
            options={
                'verbose_name': 'Mensaje WhatsApp',
                'verbose_name_plural': 'Mensajes WhatsApp',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.RunPython(seed_first_invitation_messages, migrations.RunPython.noop),
    ]
