# Generated by Django 6.0.6 on 2026-07-05 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=150, verbose_name='Nombre del Invitado')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('companions_count', models.PositiveIntegerField(default=0, verbose_name='Acompañantes Extras')),
                ('allergies_or_notes', models.TextField(blank=True, verbose_name='Alergias o Notas')),
                ('is_confirmed', models.BooleanField(default=True, verbose_name='¿Asistirá?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_confirmations', to='invitations.invitation')),
            ],
            options={
                'verbose_name': 'Confirmación de Asistencia',
                'verbose_name_plural': 'Confirmaciones (RSVP)',
                'ordering': ['-created_at'],
            },
        ),
    ]
