# Generated by Django 6.0.6 on 2026-07-05 05:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_invitation_hero_image_position'),
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Invitado/Familia')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono (WhatsApp)')),
                ('max_companions', models.PositiveIntegerField(default=0, help_text='Límite para invitados en lista.', verbose_name='Acompañantes Permitidos')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_public_rsvp', models.BooleanField(default=False, verbose_name='RSVP Público')),
                ('has_responded', models.BooleanField(default=False, verbose_name='¿Ya respondió?')),
                ('is_attending', models.BooleanField(default=False, verbose_name='¿Asistirá?')),
                ('confirmed_companions', models.PositiveIntegerField(default=0, verbose_name='Acompañantes Confirmados')),
                ('dietary_restrictions', models.TextField(blank=True, verbose_name='Restricciones Alimenticias / Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='invitations.invitation')),
            ],
            options={
                'verbose_name': 'Invitado',
                'verbose_name_plural': 'Lista de Invitados',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='GuestConfirmation',
        ),
    ]
