# Generated by Django 6.0.6 on 2026-07-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_guest_delete_guestconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='rsvp_deadline',
            field=models.DateTimeField(blank=True, help_text='Si se deja en blanco, usará la fecha límite general de la invitación.', null=True, verbose_name='Fecha Límite Personalizada'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='max_companions',
            field=models.PositiveIntegerField(default=0, help_text='Total de personas permitidas para esta familia/invitado.', verbose_name='Pases Asignados'),
        ),
    ]
