# Generated by Django 6.0.6 on 2026-07-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_guest_rsvp_deadline_alter_guest_max_companions'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='custom_pdf_message',
            field=models.TextField(blank=True, help_text='Si se deja en blanco, usará el mensaje por defecto de la invitación.', null=True, verbose_name='Mensaje de Pase PDF (Opcional)'),
        ),
    ]
