# Generated by Django 6.0.6 on 2026-07-10 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0004_guest_custom_pdf_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='custom_pdf_message',
        ),
    ]
