# Generated by Codex on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0006_guest_created_by_guest_sheet_name_guest_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='whatsapp_sent',
            field=models.BooleanField(default=False, verbose_name='WhatsApp enviado'),
        ),
    ]
