# Generated by Codex on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0007_guest_whatsapp_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alias'),
        ),
    ]
